import org.gradle.api.Plugin
import org.gradle.api.Project

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'zcfrank1st' at '12/22/16 8:56 AM' with Gradle 3.2.1
 *
 * @author zcfrank1st, @date 12/22/16 8:56 AM
 */
class WatchmanPlugin implements Plugin<Project>{

    @Override
    void apply(Project project) {

    }
}
